import Link from "next/link";
import type { Metadata } from "next";
import { ArrowDown, ArrowUpRight, Asterisk, Sparkles } from "lucide-react";
import { Header, Footer } from "@/components/SiteShell";
import { cases, industries, services } from "@/lib/content";
import { servicePages } from "@/lib/seo-content";

export const metadata:Metadata={title:"Business Process Optimisation & AI Automation | Betterflow",description:"Turn operational chaos into clear, scalable systems. We audit, redesign and automate business processes using BPMN, AI, integrations and custom software.",alternates:{canonical:"/"}};

export default function Home() {
  return <main><Header/>
    <section className="hero">
      <div className="hero-meta"><span>PROCESS OPTIMISATION & AUTOMATION STUDIO</span><span>BPMN × AI × INTEGRATIONS × DEVELOPMENT</span></div>
      <h1>Own the <span className="outline-word">chaos.</span><br/><em>Design the flow.</em></h1>
      <p className="hero-copy">Your business has outgrown the way it works. We uncover where work gets stuck, redesign the process, and build the automation and software that move it forward.</p>
      <Link className="hero-link" href="/process-assessment"><span>Show us where work gets stuck</span><ArrowUpRight/></Link>
      <div className="visual-stage" aria-hidden="true"><div className="mesh mesh-a"/><div className="mesh mesh-b"/><div className="core"><span>CHAOS</span><strong>→</strong><span>FLOW</span></div><div className="orbit"><i/><i/><i/></div><span className="stage-note note-a">01 / SEE IT</span><span className="stage-note note-b">02 / SHAPE IT</span><span className="stage-note note-c">03 / BUILD IT</span></div>
      <div className="scroll-note"><ArrowDown size={16}/> Scroll through the transformation</div>
    </section>
    <section className="story chaos-story dark-section"><div className="chapter">CHAPTER 01 <span>WHEN GROWTH BECOMES FRICTION</span></div><div className="story-grid"><h2>The chaos isn&apos;t random.<br/><em>It&apos;s a process you can&apos;t see yet.</em></h2><div><p className="lead">Teams grow. Tools multiply. Temporary workarounds quietly become the way the business runs.</p><p>You feel it as delays, duplicated work and constant questions. We see the hidden process underneath — and the opportunity to make it clear, owned and scalable.</p><div className="chaos-list"><span>THE SAME DATA ENTERED TWICE</span><span>APPROVALS WAITING ON ONE PERSON</span><span>REPORTS REBUILT BY HAND</span><span>DECISIONS LOST BETWEEN TOOLS</span></div></div></div><div className="signal"><span>01</span><div className="signal-line"/><p>Before we automate anything, we make the work visible.</p></div></section>
    <section className="method"><div className="chapter">CHAPTER 02 <span>TAKE CONTROL OF THE WORK</span></div><div className="method-title"><h2>We don&apos;t automate<br/>the <em>mess.</em></h2><p>We redesign the work first. Strategy and technical delivery stay together from the first process conversation to the working system.</p></div><div className="steps">
      {[['01','See','We listen to the people doing the work and uncover the real process — not the version written in a document.'],['02','Untangle','We map the As-Is workflow, expose bottlenecks and separate useful complexity from accidental chaos.'],['03','Design','We create the To-Be process with clear decisions, ownership, exceptions and measurable outcomes.'],['04','Build','We connect systems and implement the right automation, AI or custom software around the improved process.']].map((s,i)=><article key={s[0]} className={`step step-${i+1}`}><span>{s[0]}</span><Asterisk/><h3>{s[1]}</h3><p>{s[2]}</p></article>)}
    </div><div className="control-strip"><article><span>CLARITY</span><strong>One process your team can finally see.</strong></article><article><span>CONTROL</span><strong>Owners, decisions and exceptions made explicit.</strong></article><article><span>MOMENTUM</span><strong>Automation where it genuinely saves work.</strong></article></div></section>
    <section className="services-preview"><div className="chapter">CHAPTER 03 <span>BUSINESS PROCESS AUTOMATION SERVICES</span></div><div className="services-head"><h2>Not automation<br/>for the sake of it.</h2><p>We connect process analysis to delivery: BPMN mapping, workflow optimisation, AI agents, API integration, Bubble and custom web application development.</p></div><div className="service-list">{services.slice(0,6).map((s,i)=><Link href={`/services/${servicePages[i].slug}`} className="service-row" key={s.n}><span>{s.n}</span><h3>{servicePages[i].title}</h3><p>{servicePages[i].short}</p><ArrowUpRight/></Link>)}</div><Link className="text-link" href="/services">Explore all automation services <ArrowUpRight/></Link></section>
    <section className="industries-preview"><div className="chapter">CHAPTER 04 <span>INDUSTRY AUTOMATION EXPERIENCE</span></div><h2>Different industries.<br/><em>The same invisible friction.</em></h2><div className="industry-grid">{industries.map((item)=><Link key={item.slug} href={`/industries/${item.slug}`} className={`industry-card ${item.color}`}><span>{item.index}</span><Sparkles size={19}/><h3>{item.title}</h3><p>{item.story}</p><div>Explore automation use cases <ArrowUpRight size={18}/></div></Link>)}</div></section>
    <section className="cases-preview"><div className="chapter">CHAPTER 05 <span>PROOF, NOT PROMISES</span></div><div className="cases-head"><h2>Systems we&apos;ve<br/><em>helped move.</em></h2><Link className="text-link" href="/case-studies">All case studies <ArrowUpRight/></Link></div><div className="case-stack">{cases.slice(0,3).map((item,i)=><article className={`case-card ${item.tone}`} key={item.title}><div><span className="case-index">0{i+1}</span><span className="eyebrow">{item.type}</span></div><h3>{item.title}</h3><p>{item.text}</p><strong>{item.result}</strong></article>)}</div></section>
    <section className="home-seo"><span className="eyebrow">FROM OPERATIONAL CHAOS TO A SYSTEM YOU OWN</span><div><h2>Your process should not live in one person&apos;s head.</h2><div><p>Betterflow helps growing companies bring order to manual, fragmented and difficult-to-scale operations. We begin with a business process audit, document the real As-Is workflow and use BPMN process mapping to design a clearer To-Be process.</p><p>Then we build what the improved process needs: AI workflow automation, CRM automation, API integrations, n8n or Make workflows, Bubble solutions, data pipelines, management dashboards or custom Next.js applications. You leave with more than a diagram or another tool — you leave with a system your team can understand, operate and improve.</p><Link href="/process-assessment">Turn your stuck process into a clear next step <ArrowUpRight/></Link></div></div></section>
    <section className="quiz-home-cta"><span className="eyebrow">SEVEN QUESTIONS. A CLEARER NEXT STEP.</span><h2>Busy isn’t a business model.<br/><em>Find your way out.</em></h2><p>Discover what’s worth automating in your business — and where to start.</p><Link className="flow-button" href="/automation-check">Take the free automation check <ArrowUpRight/></Link></section>
    <Footer/>
  </main>;
}
