"use client";
import { useEffect, useRef, useState } from "react";
import Link from "next/link";
import { ArrowUpRight, ArrowLeft, Check } from "lucide-react";
import { questions, type QuizResult } from "@/lib/automation-quiz";
export default function AutomationQuiz(){
 const [step,setStep]=useState(-1),[answers,setAnswers]=useState<number[]>(Array(questions.length).fill(-1)),[email,setEmail]=useState(""),[consent,setConsent]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(""),[result,setResult]=useState<QuizResult|null>(null);
 const lastChoice=useRef(0);
 const id=useRef<string>("");const heading=useRef<HTMLHeadingElement>(null);
 useEffect(()=>{if(step>=0||result) heading.current?.focus();},[step,result]);
 async function submit(event:React.FormEvent<HTMLFormElement>){event.preventDefault();if(busy)return;setBusy(true);setError("");try{id.current ||= Array.from(crypto.getRandomValues(new Uint8Array(16)),v=>v.toString(16).padStart(2,"0")).join("").replace(/^(.{8})(.{4})(.{4})(.{4})(.{12})$/,"$1-$2-$3-$4-$5");const response=await fetch("/api/automation-check",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:id.current,email,answers,consent,website:new FormData(event.currentTarget).get("website")})});const data=await response.json();if(!response.ok)throw new Error(data.error||"Please try again.");setResult(data.result);}catch(e){setError(e instanceof Error?e.message:"Something went wrong. Please try again.");}finally{setBusy(false);}}
 return <section className="automation-quiz">
 <div className="quiz-topline"><span className="eyebrow">THE BETTERFLOW AUTOMATION CHECK</span><span>2 MINUTES / 7 QUESTIONS</span></div>
 {step===-1?<div className="quiz-start"><div><span className="quiz-kicker">LESS BUSYWORK. MORE BUSINESS.</span><h1>Does your business<br/>need <em>automation?</em></h1><p>Find out where work gets stuck — and what’s actually worth automating. Seven quick questions. One practical place to start.</p><button className="flow-button" onClick={()=>setStep(0)}>Find my opportunity <ArrowUpRight/></button><p className="quiz-small">No technical knowledge needed. Enter your email at the end to unlock your personalised result.</p></div><aside className="quiz-teaser"><span>YOUR PERSONAL ROADMAP</span><strong>From “we’re too busy”<br/>to <em>“here’s where to start.”</em></strong><ul><li><Check/> Your automation potential</li><li><Check/> Your first workflow to improve</li><li><Check/> Your practical improvement plan</li></ul><span>FREE ASSESSMENT / INSTANT ON-SCREEN RESULT</span></aside></div>:result?<div className="quiz-result"><span className="quiz-kicker">YOUR AUTOMATION SNAPSHOT</span><h1 ref={heading} tabIndex={-1}>{result.level}<em> {result.score}/100</em></h1><p>{result.description}</p><p className="quiz-small">An indicative opportunity score based on your answers, not a prediction of savings or return on investment.</p><section className="quiz-diagnosis"><span className="quiz-kicker">01 / WHERE YOU ARE TODAY</span><h2>Your current situation</h2><p>{result.situationSummary}</p><div className="quiz-priority"><strong>First priority: {result.priority.title}</strong><p>{result.priority.action}</p></div><div className="quiz-evidence">{result.situations.map(item=><article key={item.title}><h3>{item.title}</h3><span className="quiz-answer">You answered: {item.evidence}</span><p>{item.reading}</p><p><strong>What to do: </strong>{item.action}</p></article>)}</div></section>
 <section className="quiz-diagnosis"><span className="quiz-kicker">02 / YOUR FIRST PRACTICAL IMPROVEMENT</span><h2>{result.workflow.name}</h2><p>{result.workflow.idea}</p><p><strong>{result.readiness}.</strong> This is a suggested starting point based on your preferred area; validate it against the workload you measure.</p><div className="quiz-result-grid"><article><span>HOW THE WORKFLOW COULD RUN</span><p><strong>Trigger: </strong>{result.pilotDetails.trigger}</p><ol>{result.pilotDetails.steps.map(item=><li key={item}>{item}</li>)}</ol></article><article><span>KEEP A PERSON IN CONTROL</span><p>{result.pilotDetails.human}</p><h3>Measure these changes</h3><p>{result.pilotDetails.measure}</p></article></div></section>
 <section className="quiz-diagnosis"><span className="quiz-kicker">03 / A SUGGESTED FOUR-WEEK PLAN</span><h2>From answers to action</h2><p>A starting schedule, not a delivery estimate. Adjust it to your team’s capacity and the complexity of the chosen workflow.</p><div className="quiz-roadmap">{result.roadmap.map(item=><article key={item.when}><span>{item.when}</span><div><h3>{item.title}</h3><p>{item.action}</p><p><strong>You should finish with: </strong>{item.deliverable}</p></div></article>)}</div></section>
 <section className="quiz-diagnosis quiz-measure"><span className="quiz-kicker">04 / MAKE SURE IT ACTUALLY HELPS</span><h2>Measure the benefit. Avoid the trap.</h2><p>{result.measurement}</p><h3>What to avoid right now</h3><p>{result.avoid}</p><p className="quiz-small">This assessment uses only your seven answers. It does not inspect your tools, data quality, budget or requirements. Confirm these before selecting software or estimating savings.</p></section><Link className="flow-button" href="/process-assessment">Let’s map this process <ArrowUpRight/></Link><button className="quiz-back" onClick={()=>{setStep(0);setResult(null);id.current="";}}>Retake the assessment</button></div>:<div className="quiz-workspace"><div className="quiz-progress-label"><span>{step<questions.length?`QUESTION ${step+1} OF ${questions.length}`:"YOUR RESULT IS READY TO UNLOCK"}</span><span>{Math.round(Math.min(step,questions.length)/questions.length*100)}%</span></div><progress max={questions.length} value={Math.min(step,questions.length)} aria-label="Assessment progress"/>
 {step<questions.length?<><h1 ref={heading} tabIndex={-1}>{questions[step].title}</h1><p>{questions[step].hint}</p><p className="quiz-small">Choose one answer to continue automatically.</p><div className="quiz-options" role="group" aria-label={questions[step].title}>{questions[step].options.map((o,i)=><button key={`${step}-${i}`} aria-pressed={answers[step]===i} className={answers[step]===i?"selected":""} onClick={()=>{const now=Date.now();if(now-lastChoice.current<350)return;lastChoice.current=now;setAnswers(a=>a.map((v,k)=>k===step?i:v));setStep(s=>s+1);}}><span className="option-index">0{i+1}</span><span>{o}</span>{answers[step]===i?<Check/>:<ArrowUpRight/>}</button>)}</div><div className="quiz-actions"><button className="quiz-back" onClick={()=>setStep(s=>s-1)}><ArrowLeft/> Back</button></div></>:<><h1 ref={heading} tabIndex={-1}>Less guesswork.<br/><em>Your next move.</em></h1><p>Enter your email to reveal your automation potential, a detailed picture of your current situation and a practical improvement plan here on this page.</p><form className="quiz-email" onSubmit={submit}><label htmlFor="quiz-email">Your email</label><input id="quiz-email" name="email" type="email" autoComplete="email" placeholder="you@company.com" maxLength={254} required value={email} onChange={e=>setEmail(e.target.value)}/><div className="quiz-trap" aria-hidden="true"><label>Website<input name="website" tabIndex={-1} autoComplete="off"/></label></div><label className="quiz-consent"><input type="checkbox" required checked={consent} onChange={e=>setConsent(e.target.checked)}/><span>I agree that Betterflow may store my email and answers to provide this assessment. This does not subscribe me to marketing emails.</span></label>{error&&<p role="alert" className="quiz-error">{error}</p>}<button className="flow-button" disabled={busy}>{busy?"Preparing your result…":"Reveal my automation roadmap"}<ArrowUpRight/></button></form><button className="quiz-back" disabled={busy} onClick={()=>setStep(questions.length-1)}><ArrowLeft/> Review my answers</button></>}
 </div>}
 </section>;
}
