export const questions = [
 {title:"How much time goes into repetitive work each week?",hint:"Think copying data, updating spreadsheets, sending reminders and building reports across your team.",options:["Less than 2 hours","2–5 hours","6–15 hours","More than 15 hours"]},
 {title:"How often does information get copied between tools?",hint:"For example, from an email to a spreadsheet, then into your CRM.",options:["Rarely or never","A few times a week","Every day","Many times a day"]},
 {title:"What happens when the person who knows the process is away?",hint:"Consider approvals, onboarding, reporting or following up with customers.",options:["Work continues smoothly","Someone needs a quick handover","Work slows down significantly","The process stops"]},
 {title:"How often do manual errors or missed follow-ups cause rework?",hint:"Include wrong details, duplicate entries, late responses and forgotten tasks.",options:["Rarely","A few times a month","Every week","Most days"]},
 {title:"Could your team handle twice the volume tomorrow?",hint:"Assume the same people and the same tools.",options:["Yes, comfortably","Yes, with some adjustments","Only with extra hours","We would need to hire immediately"]},
 {title:"How clearly is your main workflow defined?",hint:"Automation works best when the team agrees on the steps and the exceptions.",options:["Clear steps, owners and exceptions","Mostly consistent, not fully documented","Different people do it differently","It changes every time"]},
 {title:"Where would you most like to get time back?",hint:"We’ll use this to suggest a practical first workflow.",options:["Leads and customer follow-ups","Client onboarding and delivery","Reporting and data entry","Internal tasks and approvals"]},
];
export function getQuizResult(answers:number[]) {
 const score=Math.round(answers.slice(0,5).reduce((a,b)=>a+b,0)/15*100);
 const needsMapping=answers[5]>=2;
 const level=score>=67?"High automation potential":score>=34?"A few strong opportunities":"Keep it focused";
 const description=score>=67?"Repetitive work is creating real friction. Start with one frequent, measurable workflow before expanding across the business.":score>=34?"Your business has useful opportunities for automation. A small, well-chosen workflow is a better starting point than a major overhaul.":"Your answers suggest limited manual friction today. Avoid adding complexity: automate only a recurring task with a clear benefit.";
 const workflows=[{name:"Lead follow-up",idea:"Connect an enquiry to your CRM, assign an owner and create a follow-up reminder. Keep a person in control of important customer messages."},{name:"Client onboarding",idea:"Turn an approved project into a checklist, document request and task handover. Define what happens when information is missing."},{name:"Reporting and data entry",idea:"Bring one recurring report’s source data into a single view, with checks for missing or duplicate records before it is shared."},{name:"Internal approvals",idea:"Route a request to the right owner, track its status and remind people when an agreed deadline is approaching."}];
 const workflow=workflows[answers[6]];
 const situations=[
  {title:"Time spent on repetitive work",evidence:questions[0].options[answers[0]],reading:["Repetitive work currently takes little time. A complex automation may cost more effort to maintain than it saves.","There is a recurring time cost, but it is worth measuring individual tasks before buying tools.","Manual work takes a meaningful share of the team’s week. A frequent, predictable task is a sensible place to investigate.","Repetitive work takes more than 15 team-hours each week. This points to a substantial workload, although not all of it will be automatable."][answers[0]],action:answers[0]<2?"Track each recurring task for five working days; record frequency and minutes per run.":"List the three most time-consuming recurring tasks. Measure time per run and weekly volume to choose the first pilot."},
  {title:"Information moving between tools",evidence:questions[1].options[answers[1]],reading:answers[1]<2?"Frequent data copying does not appear to be your main bottleneck. Avoid integrations without a clear recurring need.":"Your team repeatedly carries information between tools. This creates extra work and opportunities for records to disagree.",action:answers[1]<2?"Keep one agreed source for each important field; connect tools only where a repeated transfer warrants it.":"Choose one transfer. Define the source record, a unique ID, required fields and what should happen when the destination is unavailable."},
  {title:"Dependence on a key person",evidence:questions[2].options[answers[2]],reading:answers[2]<2?"Work can continue when the main owner is away, which gives you a useful foundation for delegation.":"Progress depends on one person’s knowledge or availability. Automation alone will not resolve unclear ownership or missing decisions.",action:answers[2]<2?"Write down the handover and name a backup owner so the process remains repeatable.":"Document the steps and decision rules, then have a backup owner complete one real case without help. Update the gaps they find."},
  {title:"Errors and missed follow-ups",evidence:questions[3].options[answers[3]],reading:answers[3]<2?"You report relatively infrequent rework. Protect that reliability when introducing any automation.":"Rework happens regularly. Removing manual steps could help, but speeding up a flawed process may multiply its mistakes.",action:answers[3]<2?"Record today’s error rate and review early automated runs against it.":"Log the next five errors or missed follow-ups. Fix the most common cause with required fields, duplicate checks or an owner and due date."},
  {title:"Capacity to handle growth",evidence:questions[4].options[answers[4]],reading:answers[4]<2?"Your team reports some room to absorb growth. Optimise selectively rather than rebuilding everything now.":"A rise in volume would require extra hours or people. Find the step that scales directly with each new customer or request.",action:answers[4]<2?"Track turnaround time as volume grows and set a threshold for revisiting the workflow.":"Count incoming requests and completions per week. Identify where the queue grows, then reduce manual work at that step first."},
  {title:"Process clarity",evidence:questions[5].options[answers[5]],reading:needsMapping?"The workflow is inconsistent. This makes an automation difficult to specify, test and maintain.":"Your workflow is reasonably consistent. The next step is to confirm owners, exceptions and test cases.",action:needsMapping?"Agree on one standard path, name the owner of each step and write down the exceptions before connecting any tools.":"Review the existing process with the people doing the work and add missing exceptions before building a small pilot."}
 ];
 const priority=needsMapping?5:answers.slice(0,5).indexOf(Math.max(...answers.slice(0,5)));
 const situationSummary=score<34
  ? "Your answers describe a business with relatively limited manual friction today. The strongest move is to protect what already works and test only a small improvement with a measurable benefit."
  : "Your answers suggest that "+(answers[0]>=2?"repetitive tasks take a meaningful amount of team time":"the main friction may be less about total hours and more about how work moves")+". "+(answers[2]>=2?"Work also slows or stops when a key person is away, so clearer ownership and handovers matter alongside technology. ":"")+(answers[3]>=2?"Recurring errors or missed follow-ups add a second layer of work. ":"")+(answers[4]>=2?"With the current setup, growth would put more pressure on the team.":"You still report some capacity to handle growth, so there is room to improve one workflow at a time.");
 const pilotDetails=[
  {trigger:"A new enquiry arrives through your main contact channel.",steps:["Create or update one CRM record using the email address or another agreed unique identifier.","Assign an owner and create a follow-up task with your agreed response deadline.","Show overdue enquiries in one queue and alert the backup owner."],human:"Keep qualification, pricing and sensitive customer replies with a person. Review duplicates and incomplete enquiries before acting.",measure:"Time to first human response; enquiries with no owner; overdue follow-ups."},
  {trigger:"A client confirms the project and the onboarding owner marks it ready.",steps:["Create a standard onboarding checklist from the agreed service template.","Request the required documents and details once, with clear due dates.","Create the delivery handover only after the required information is complete."],human:"Have the delivery owner approve scope, exceptions and the final handover. Do not treat missing documents as completed tasks.",measure:"Days from confirmation to ready-for-delivery; missing documents; manual reminders per client."},
  {trigger:"The agreed reporting deadline arrives.",steps:["Collect one report’s data from the agreed source systems.","Check required fields, duplicate records and whether the data is up to date.","Prepare a draft report and flag exceptions for review before sharing it."],human:"Keep a named reviewer for discrepancies and release approval. Do not silently substitute missing values with zeros.",measure:"Minutes spent preparing each report; corrections after review; reports delivered on time."},
  {trigger:"A team member submits a complete internal request.",steps:["Route the request to the owner using agreed rules such as request type or value.","Record the decision, status and due date in one shared queue.","Remind the owner before the deadline and route overdue items to a named backup."],human:"Keep approval authority with the right person. Route unusual or high-impact requests for explicit review.",measure:"Median approval time; overdue requests; requests returned for missing information."}
 ][answers[6]];
 const roadmap=[
  {when:"Days 1–3",title:needsMapping?"Make the process consistent":"Define a small, measurable pilot",action:needsMapping?"Walk through three recent cases with the people doing the work. Agree on a standard path, owners and exceptions; separate cases that genuinely need judgement.":"Choose one recurring workflow, document its trigger and finish point, and name an owner. Keep unusual cases outside the initial pilot.",deliverable:"A one-page process map, a named owner and a short list of exceptions."},
  {when:"Days 4–7",title:"Measure the current situation",action:"Record task volume, minutes of manual work, waiting time and errors for one working week. "+situations[priority].action,deliverable:"A baseline log and one agreed success target based on your actual workload."},
  {when:"Week 2",title:score<34?"Test whether a change is worth it":"Build and test one safe improvement",action:score<34?"Try a checklist, template or built-in reminder first. Only add an integration if the baseline shows enough recurring work to justify it.":"Implement only the first useful part of the suggested workflow. Test a normal case, a duplicate, missing information and a tool failure. Keep a manual fallback and an error queue.",deliverable:"A small tested improvement, with an owner who can pause it and recover failed cases."},
  {when:"Weeks 3–4",title:"Compare, refine, then decide",action:"Run the pilot with a limited set of real cases. Compare the same measures against your baseline, including time spent checking and fixing the automation. Expand only if the benefit is clear and reliability holds.",deliverable:"A keep, improve or stop decision supported by the pilot results."}
 ];
 return {score,level,description,workflow,readiness:needsMapping?"Process clarity comes first":"Ready to explore a small pilot",situationSummary,situations,priority:{title:situations[priority].title,action:situations[priority].action},pilotDetails,roadmap,
 avoid:needsMapping?"Do not automate the entire workflow while people still disagree on how it should run. First standardise the repeatable part; leave genuine exceptions with a person.":score<34?"Do not commit to a new platform or a large build before the time and maintenance costs justify it. A template or a rule in a tool you already use may be enough.":"Do not connect every system at once or remove human checks immediately. Start with one handoff, give failures an owner and keep a way to return to the manual process.",
 measurement:"Weekly net time saved = (manual minutes per case before − manual minutes per case during the pilot) × weekly case volume − weekly maintenance time. Include review and rework in the pilot time, and check that errors and turnaround time have not worsened."};
}
export type QuizResult = ReturnType<typeof getQuizResult>;
