export const services = [
  { n: "01", title: "Process discovery & BPMN", text: "We turn scattered conversations, spreadsheets and tribal knowledge into a process everyone can finally see — As-Is, To-Be and ready to improve.", tags: ["Process audit", "BPMN mapping", "Automation roadmap"] },
  { n: "02", title: "AI workflow automation", text: "We build intelligent workflows that read, decide, generate, route and follow up — without adding another manual task to your team.", tags: ["AI agents", "Document AI", "CRM workflows"] },
  { n: "03", title: "Custom web applications", text: "When off-the-shelf software cannot follow the way your business works, we build the system around the process — not the other way round.", tags: ["Next.js", "Business portals", "Internal tools"] },
  { n: "04", title: "No-code & low-code development", text: "Fast, flexible products in Bubble and modern low-code stacks — designed with a clear path to scale, ownership and future AI-assisted changes.", tags: ["Bubble", "Rapid delivery", "Modernisation"] },
  { n: "05", title: "APIs & system integration", text: "We connect the tools your team already uses so customer, operational and financial data can move without copying, pasting or getting lost.", tags: ["API integration", "n8n / Make", "Data sync"] },
  { n: "06", title: "Data, BI & AI insights", text: "We bring fragmented data into one reliable view, automate reporting and build AI interfaces that answer real management questions.", tags: ["Data warehouse", "Dashboards", "AI analytics"] },
  { n: "07", title: "CRM & lifecycle automation", text: "From the first enquiry to onboarding, retention and reactivation, we design a lifecycle that feels personal without being manual.", tags: ["Lead routing", "Onboarding", "Retention"] },
  { n: "08", title: "Product & technical delivery", text: "We translate business intent into architecture, priorities and a shippable system — then manage delivery until it works in the real world.", tags: ["Product strategy", "Technical PM", "Implementation"] },
];

export const industries = [
  { slug: "fintech-trading", title: "Fintech & Trading", index: "01", color: "blue", story: "When payouts, risk, affiliate data and customer journeys live in different systems, every decision takes too long.", work: "We connect trading, CRM, payment and marketing data into one controlled operational flow.", cases: ["Prop firm intelligence platform", "Broker reporting automation", "Trading customer lifecycle"] },
  { slug: "professional-services", title: "Professional Services", index: "02", color: "lime", story: "The work is expert. The delivery around it should not depend on documents being chased by hand.", work: "We automate qualification, proposals, SOWs, onboarding, approvals, delivery and client reporting.", cases: ["SOW workflow platform", "Client onboarding system", "Automated service delivery"] },
  { slug: "marketplaces", title: "Marketplaces & Platforms", index: "03", color: "violet", story: "Two-sided platforms become complicated long before they become large.", work: "We design onboarding, matching, search, booking, payments, messaging and admin operations as one system.", cases: ["AI expert matching", "Marketplace operations", "Search and booking flow"] },
  { slug: "education-childcare", title: "Education & Childcare", index: "04", color: "orange", story: "Educators should spend time with people, not retyping observations and managing fragmented records.", work: "We automate assessment, scheduling, reporting, voice notes, documents and parent communication.", cases: ["AI essay assessment", "Childcare voice documentation", "Tutoring operations"] },
  { slug: "experts-coaches", title: "Experts, Coaches & Consultants", index: "05", color: "pink", story: "A personal brand grows — and suddenly the expert becomes the booking tool, CRM and support desk.", work: "We automate lead qualification, booking, diagnostics, onboarding, recommendations and programme delivery without losing the personal voice.", cases: ["Expert diagnostic funnel", "AI client onboarding", "Membership operations"] },
  { slug: "content-businesses", title: "Social Media & Content", index: "06", color: "cyan", story: "Content looks creative on the outside. Behind it sits a repeating production operation.", work: "We build connected workflows for research, ideas, approvals, repurposing, publishing, lead capture and reporting.", cases: ["AI content workflow", "Multi-channel repurposing", "Social reporting automation"] },
];

export const cases = [
  { type: "FINTECH / BI", title: "From fragmented data to one management conversation", text: "A prop trading business needed more than another dashboard. We designed a central intelligence layer connecting sales, customer lifecycle, affiliate performance, trading risk and payout exposure.", result: "One source of truth", tone: "case-blue" },
  { type: "MARKETPLACE / AI", title: "Turning expert discovery into an intelligent matching flow", text: "A complex taxonomy became a searchable experience that understands the buyer's request, explains the match and opens the right specialism without adding friction.", result: "Faster discovery", tone: "case-violet" },
  { type: "PROFESSIONAL SERVICES", title: "Replacing document chasing with a controlled SOW workflow", text: "We mapped the path from onboarding and MSA to milestones, approvals, subcontractors and archiving — then shaped it into one operational product.", result: "Visible delivery", tone: "case-lime" },
  { type: "EDUCATION / AI", title: "Letting a voice note become compliant documentation", text: "We designed a secure flow from recording and transcription to PII scrubbing, two purpose-built AI outputs, human review and storage.", result: "Minutes, not admin hours", tone: "case-orange" },
];
