import type { Metadata } from "next";
import { notFound } from "next/navigation";
import Link from "next/link";
import { ArrowLeft, ArrowUpRight } from "lucide-react";
import { Header, Footer } from "@/components/SiteShell";
import { SeoBody, SeoCta } from "@/components/SeoSections";
import { articles, igorArticleSlugs } from "@/lib/seo-content";
export function generateStaticParams(){return articles.map(x=>({slug:x.slug}))}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const {slug}=await params;const p=articles.find(x=>x.slug===slug);if(!p)return {};const byIgor=igorArticleSlugs.has(slug);return {title:`${p.title} | Betterflow`,description:p.meta,alternates:{canonical:`/insights/${p.slug}`},authors:[{name:byIgor?"Igor Bodrichenko":"Jane Bodrichenko",url:byIgor?"https://www.linkedin.com/in/igor-bodrichenko-60b092212":"https://www.linkedin.com/in/jane-bodrichenko-58862a130"}]}}
export default async function Article({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const p=articles.find(x=>x.slug===slug);if(!p)notFound();const byIgor=igorArticleSlugs.has(slug);const author=byIgor?{name:"Igor Bodrichenko",url:"https://www.linkedin.com/in/igor-bodrichenko-60b092212",bio:"AI automation and development specialist working across intelligent workflows, API integrations, custom web applications, data systems and modern low-code platforms."}:{name:"Jane Bodrichenko",url:"https://www.linkedin.com/in/jane-bodrichenko-58862a130",bio:"Technical product and delivery specialist working across business process analysis, automation, AI products, data and operational systems. Her experience includes fintech, trading, marketplaces, professional services and education platforms."};const schema={"@context":"https://schema.org","@type":"Article",headline:p.title,description:p.meta,datePublished:"2026-09-08",dateModified:"2026-09-08",author:{"@type":"Person",name:author.name,url:author.url},publisher:{"@type":"Organization",name:"Betterflow"},mainEntityOfPage:`https://process-automation-studio.panchenkooo71.chatgpt.site/insights/${p.slug}`};return <main><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema)}}/><Header/><article className="article-hero"><Link href="/insights"><ArrowLeft/> All insights</Link><div><span className="eyebrow">{byIgor?"AI AUTOMATION & DEVELOPMENT GUIDE":"BUSINESS PROCESS AUTOMATION GUIDE"}</span><h1>{p.title}</h1><p>{p.excerpt}</p><div className="article-meta"><span>By {author.name}</span><span>{p.date}</span><span>{p.read}</span></div></div></article><SeoBody sections={p.sections}/><section className={`author-box ${byIgor?"author-igor":""}`}><span>ABOUT THE AUTHOR</span><h2>{author.name}</h2><p>{author.bio}</p><a href={author.url} target="_blank" rel="noreferrer">View {byIgor?"Igor's":"Jane's"} LinkedIn profile <ArrowUpRight/></a></section><SeoCta/><Footer/></main>}
